name: Pages
on:
  push:
    branches: [main,tz]

jobs:
  pages:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Node.js environment
        uses: actions/setup-node@v2.3.0

      - name: Checkout branch
        uses: actions/checkout@v2
        with:
          path: ${{github.ref}}

      - name: Install and build
        run: |
          yarn --frozen-lockfile
          yarn build --base /build-userfriendly-cli-tool-talk/$(basename ${{github.ref}})/
        working-directory: ${{github.ref}}

      - name: Checkout pages
        uses: actions/checkout@v2
        with:
          ref: pages
          path: pages

      - name: Commit and push pages
        run: |
          rm -rf ${{github.ref}}
          mkdir $(basename ${{github.ref}})
          mv ../${{github.ref}}/dist/* $(basename ${{github.ref}})
          git add .
          git diff --staged --quiet --exit-code && exit # no changes
          git config user.name "Nicolas Lepage (actions)"
          git config user.email 19571875+nlepage@users.noreply.github.com
          git commit -m "$MESSAGE"
          git push
        working-directory: pages
        env:
          MESSAGE: ${{github.event.commits[0].message}}
