name: Pages
on:
  push:
    branches: [ main ]

jobs:
  pages:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          path: main
      
      - name: Setup Node.js environment
        uses: actions/setup-node@v2.3.0

      - name: Install dependencies
        run: yarn
        working-directory: main
        
      - name: Build
        run: yarn build --base /build-userfriendly-cli-tool-talk/
        working-directory: main
